---
title: "COVID-19 on Diferent Aspects from Toronto Cases"
author: "Zhendong Zhang"
date: 2020-09-26
output: html_document
---



<div id="abstract" class="section level1">
<h1>Abstract</h1>
<p>In this paper I will explore the data of COVID-19 cases from Toronto, and analyzing it in different aspects such as gender groups, age groups, fatal and resolved cases. Also, I will develop a model to pursue deeper influences from the variables and to know the level of influences by each variable.</p>
<pre class="r"><code>resou &lt;- list_package_resources(&quot;https://open.toronto.ca/dataset/covid-19-cases-in-toronto/&quot;)
covdat &lt;- get_resource(resou)
str(covdat)</code></pre>
<pre><code>## tibble [17,872 x 18] (S3: tbl_df/tbl/data.frame)
##  $ _id                   : int [1:17872] 143647 143648 143649 143650 143651 143652 143653 143654 143655 143656 ...
##  $ Assigned_ID           : int [1:17872] 1 2 3 4 5 6 7 8 9 10 ...
##  $ Outbreak Associated   : chr [1:17872] &quot;Sporadic&quot; &quot;Sporadic&quot; &quot;Sporadic&quot; &quot;Sporadic&quot; ...
##  $ Age Group             : chr [1:17872] &quot;50 to 59 Years&quot; &quot;50 to 59 Years&quot; &quot;20 to 29 Years&quot; &quot;60 to 69 Years&quot; ...
##  $ Neighbourhood Name    : chr [1:17872] &quot;Willowdale East&quot; &quot;Willowdale East&quot; &quot;Parkwoods-Donalda&quot; &quot;Church-Yonge Corridor&quot; ...
##  $ FSA                   : chr [1:17872] &quot;M2N&quot; &quot;M2N&quot; &quot;M3A&quot; &quot;M4W&quot; ...
##  $ Source of Infection   : chr [1:17872] &quot;Travel&quot; &quot;Travel&quot; &quot;Travel&quot; &quot;Travel&quot; ...
##  $ Classification        : chr [1:17872] &quot;CONFIRMED&quot; &quot;CONFIRMED&quot; &quot;CONFIRMED&quot; &quot;CONFIRMED&quot; ...
##  $ Episode Date          : chr [1:17872] &quot;2020-01-22&quot; &quot;2020-01-21&quot; &quot;2020-02-05&quot; &quot;2020-02-16&quot; ...
##  $ Reported Date         : chr [1:17872] &quot;2020-01-23&quot; &quot;2020-01-23&quot; &quot;2020-02-21&quot; &quot;2020-02-25&quot; ...
##  $ Client Gender         : chr [1:17872] &quot;FEMALE&quot; &quot;MALE&quot; &quot;FEMALE&quot; &quot;FEMALE&quot; ...
##  $ Outcome               : chr [1:17872] &quot;RESOLVED&quot; &quot;RESOLVED&quot; &quot;RESOLVED&quot; &quot;RESOLVED&quot; ...
##  $ Currently Hospitalized: chr [1:17872] &quot;No&quot; &quot;No&quot; &quot;No&quot; &quot;No&quot; ...
##  $ Currently in ICU      : chr [1:17872] &quot;No&quot; &quot;No&quot; &quot;No&quot; &quot;No&quot; ...
##  $ Currently Intubated   : chr [1:17872] &quot;No&quot; &quot;No&quot; &quot;No&quot; &quot;No&quot; ...
##  $ Ever Hospitalized     : chr [1:17872] &quot;No&quot; &quot;Yes&quot; &quot;No&quot; &quot;No&quot; ...
##  $ Ever in ICU           : chr [1:17872] &quot;No&quot; &quot;No&quot; &quot;No&quot; &quot;No&quot; ...
##  $ Ever Intubated        : chr [1:17872] &quot;No&quot; &quot;No&quot; &quot;No&quot; &quot;No&quot; ...</code></pre>
<pre class="r"><code>variable.names(covdat)</code></pre>
<pre><code>##  [1] &quot;_id&quot;                    &quot;Assigned_ID&quot;            &quot;Outbreak Associated&quot;   
##  [4] &quot;Age Group&quot;              &quot;Neighbourhood Name&quot;     &quot;FSA&quot;                   
##  [7] &quot;Source of Infection&quot;    &quot;Classification&quot;         &quot;Episode Date&quot;          
## [10] &quot;Reported Date&quot;          &quot;Client Gender&quot;          &quot;Outcome&quot;               
## [13] &quot;Currently Hospitalized&quot; &quot;Currently in ICU&quot;       &quot;Currently Intubated&quot;   
## [16] &quot;Ever Hospitalized&quot;      &quot;Ever in ICU&quot;            &quot;Ever Intubated&quot;</code></pre>
<p>The dataset(covdat) is total reported cases of COVID-19 in Toronto<br />
</p>
<p>Episode Date is an estimate of symptom onset date in a case. It is calculated hierarchically based
on either the date of symptom onset, specimen collection/test date, or the date reported to
public health.<br />
</p>
<p>Reported Date is the date the case was reported to public health.<br />
</p>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>The major event in the year 2020 is the outbreak of COVID-19. It has significantly changed our life. In this paper, I will explore the influence of COVID-19 on different groups of people in Toronto. And also the effectiveness of the response of Government. This paper is mainly based on the confirmed cases` data from Toronto.<br />
</p>
<p>I mainly compared the data from each group of people such as male, female, resolved cases and fatal cases. Then I tried to find out the characteristics in each group and found out the possible reasons behind these data. The major found is that most fatal cases in the Toronto area are elder people, and this disease has indiscriminate influences across different genders.<br />
</p>
<p>First, I traced the curve of the outbreak from Jan 2020 until now and the distribution of cases on each age group in Toronto. Then I analyzed the sources of infections on these cases, and I trace the closed contacted cases curve to see if the policy is effective. In the end, I mainly focus on the fatal and resolved cases and tried to analyze the characteristics behind these two groups. In the future I will keep monitoring the cases in Toronto, seeing if there is another event worth analyzing. This paper`s weakness is that I omit lots of cases that the data related are not available so we cannot trace them, but there might be a major influence in these cases, which could significantly influence our conclusion. Also, the data sample is too small since we only have Toronto data. In the end, I developed a tree-based model on predicting the possibilities of outcomes for a confirmed case.<br />
</p>
<p>My source code is here: <a href="https://github.com/Craymate/Blog-datafield/blob/master/content/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases.Rmd" class="uri">https://github.com/Craymate/Blog-datafield/blob/master/content/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases.Rmd</a></p>
</div>
<div id="for-overall-cases" class="section level1">
<h1><span style="color:purple">For Overall Cases:</span></h1>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/infect-month-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The peak is in April, and started to decrease in May. There was a boost from March to April. Then it has been decreased to the level in March. But now it shows a sign of increasing again.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/infect-age-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The infection between age groups is nearly normal distributed.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/infect-gender-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Different gender groups have slightly differences in infected amount.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/source-plots-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>There are many cases that they are NA-Outbreak Associated, which means that we don`t know the source of infection on these cases.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/filtered-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The highest source of infection is close contact, which is significant higher than others.
And the second highest is the community.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/covdat-contact-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Since April 1st, there was an emergency response from Ontario Government. But the close contact confirmed cases increases to the peak in May. Then this policy starts to take effect in June, and making significant effect in the following three months until now. In September , it shows a sign of increasing with the number of close contact cases is also increased.</p>
<pre class="r"><code>full_contact &lt;- c(0,0,contact_case$count)
cor.test(full_contact, total_case$count)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  full_contact and total_case$count
## t = 4.9282, df = 7, p-value = 0.001698
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.5229006 0.9747969
## sample estimates:
##       cor 
## 0.8810577</code></pre>
<p>Low P-value from result of cor.test() means total cases is related to close contact cases.
The sample estimates means that the total cases are estimated 88.1% related by closed contact cases.
This means social distancing is expected to be a right strategy on this outbreak.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/total-outcome-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The majority outcomes are resolved.</p>
</div>
<div id="for-fatal-cases" class="section level1">
<h1><span style="color:red">For Fatal Cases:</span></h1>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/fata-age-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Most of cases are elder people. This is reasonable because they generally have weaker health conditions. As the age increases, the fatal cases also increase.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/fata-gender-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Different gender groups have slightly differences on the fatal outcomes</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/fata-gender-percent-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>##    Gender      Ratio
## 1  FEMALE 0.06926357
## 2    MALE 0.06868313
## 3 UNKNOWN 0.14977974</code></pre>
<p>(The fatal ratio are calculated by the ratio between fatal and total cases from each groups.)<br />
Gender makes no influence between Male and Female. Unknown`s fatal rate is high, because the total amount of samples from Unknown is small.</p>
<pre class="r"><code>fata_mean &lt;- mean(gender_fata_ratio$Ratio)
fata_mean</code></pre>
<pre><code>## [1] 0.09590881</code></pre>
<p>There is an approximately 9.6% <span style="color:red">Fatal Rate</span>.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/fata-hosip-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Nearly half of fatal cases have ever hospitalized.</p>
<pre class="r"><code>percent &lt;- (summ1$Ever_Hospitalized + summ1$Ever_in_ICU + summ1$Ever_Intubated) * 100/summ1$Total
percent</code></pre>
<pre><code>##          n
## 1 71.34199</code></pre>
<p>And about 71% of total fatal cases got treated. This indicates that the shortage of hospital resources to general extent.</p>
</div>
<div id="for-resolved-cases" class="section level1">
<h1><span style="color:blue">For Resolved Cases:</span></h1>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/resol-age-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Younger people seems more likely to recover from this.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/resol-gender-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Different gender groups also have slightly differences on the resolved outcomes</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/resol-gender-percent-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>(The rates are calculated by the ratio between resolved and total cases from each groups.)<br />
Gender nearly makes no influence among different gender groups.</p>
<pre class="r"><code>resol_mean &lt;- mean(gender_resol_ratio$Ratio)
resol_mean</code></pre>
<pre><code>## [1] 0.9051085</code></pre>
<p>There is an approximately 90.5% <span style="color:blue">Resolved Rate</span>.</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/resol-hosip-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We can see that in most resolved cases, people can recover without even being hospitalized.
So immune system is making a great effect in this outbreak.</p>
</div>
<div id="classification-tree-model" class="section level1">
<h1><span style="color:green">Classification Tree Model:</span></h1>
<p>This is a classification tree based model on predicting the chance you can recover from COVID-19.<br />
I build this model by using 60% of total cases for training, and test the model on the remaining 40%.<br />
I cleaned the active cases and made data binomial. This means in the result section, 1 is for Resolved, and 0 is for Fatal.<br />
I used “Age Group”, “Ever Hospitalized”, “Ever in ICU”, “Ever Intubated”, “Neighbourhood Name”, “FSA” as my variables. I do not use gender as a variable becuase it has no ifluence on the outcomes, as well as source of infections.<br />
</p>
<p><span style="color:red">Attention:</span> This model is only for study, the result does`t represent real outcome in reality.<br />
<br />
<span style="color:red">Pre-condition:</span> The input cases must be confirmed.</p>
<pre class="r"><code>test[1,]</code></pre>
<pre><code>## # A tibble: 1 x 6
##   `Age Group` `Ever Hospitali~ `Ever in ICU` `Ever Intubated` `Neighbourhood ~
##   &lt;chr&gt;       &lt;chr&gt;            &lt;chr&gt;         &lt;chr&gt;            &lt;chr&gt;           
## 1 30 to 39 Y~ No               No            No               Don Valley Vill~
## # ... with 1 more variable: FSA &lt;chr&gt;</code></pre>
<p>The input vector is as above.
FSA stands for the patient`s first three letter of postal code.</p>
<pre class="r"><code>nrow(train)</code></pre>
<pre><code>## [1] 9193</code></pre>
<pre class="r"><code>nrow(test)</code></pre>
<pre><code>## [1] 6129</code></pre>
<p>There are total 9193 training cases.
There are total 6129 testing cases.<br />
</p>
<p><img src="/post/2020-09-20-research-of-covid-19-on-diferent-aspects-from-toronto-cases_files/figure-html/test-mod-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Here is the Tree Model Plot: <a href="https://github.com/Craymate/Blog-datafield/blob/master/content/post/Tree%20Model.pdf" class="uri">https://github.com/Craymate/Blog-datafield/blob/master/content/post/Tree%20Model.pdf</a></p>
<pre class="r"><code>Pred &lt;- predict(tree, test, type = &quot;class&quot;)
Reference &lt;- as.matrix(result)
confusionMatrix(table(Pred, result))</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##     result
## Pred    0    1
##    0   81   36
##    1  105 5907
##                                           
##                Accuracy : 0.977           
##                  95% CI : (0.9729, 0.9806)
##     No Information Rate : 0.9697          
##     P-Value [Acc &gt; NIR] : 0.0002864       
##                                           
##                   Kappa : 0.5235          
##                                           
##  Mcnemar&#39;s Test P-Value : 1.024e-08       
##                                           
##             Sensitivity : 0.43548         
##             Specificity : 0.99394         
##          Pos Pred Value : 0.69231         
##          Neg Pred Value : 0.98253         
##              Prevalence : 0.03035         
##          Detection Rate : 0.01322         
##    Detection Prevalence : 0.01909         
##       Balanced Accuracy : 0.71471         
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<p>The rate of accuracy is approximately 97.7%.<br />
And there are 105 cases actually fatal but predicted resolved.<br />
And there are 36 cases actually resolved but predicted fatal.<br />
</p>
<p><span style="color:green">Here we can try to create cases to see their outcomes.</span><br />
</p>
<p>The first case is in “20 to 29 years” age group.And not ever in ICU, Hospitalized, Intubated.<br />
Neighbourhood is “Little Portugal”<br />
FSA is “M6K”<br />
</p>
<p>The second case is in “80 to 89 Years” age group. And the rest are same<br />
</p>
<p>The third case is in “80 to 89 Year” And have ever in ICU, Hospitalized, Intubated.<br />
Neighbourhood is “Victoria Village”<br />
FSA is “M4A”<br />
<br />
</p>
<pre class="r"><code>predict(tree, try1)</code></pre>
<pre><code>##            0         1
## 1 0.00751814 0.9924819</code></pre>
<p>Then we can plug the first case into the model.<br />
The outcome is 0.75% to be fatal and 99.25% to be resolved.<br />
</p>
<pre class="r"><code>predict(tree, try2)</code></pre>
<pre><code>##           0         1
## 1 0.2130909 0.7869091</code></pre>
<p>The second case which has an older age, has 21.3% chance to be fatal, and 78.7% to be resolved.<br />
In this case, we can identify the age influences on the outcome.<br />
</p>
<pre class="r"><code>predict(tree, try3)</code></pre>
<pre><code>##           0         1
## 1 0.8823529 0.1176471</code></pre>
<p>The third case has the same age with the second one. But changed the location and the medical history.<br />
The outcome becomes 88.24% to be fatal and 11.76% to be resolved.<br />
</p>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<p>COVID-19 is making no difference on different gender groups, but age groups. Elder people cases are more likely to be fatal based on Toronto data. And recovery of this disease is heavily based on immune system. Also, every age group could have equally chance to get infected.<br />
</p>
<p>Despite the unknown source of infection cases, the major source is close contact. The government published a law in April to enforce social distancing. This law is making its effect in June, and it is effective. The level of confirmed cases in Toronto in Sept shows the sign of increasing now.<br />
</p>
<p>We can identify the influences of medical history from COVID-19 in the tree model, as well as the influences by age. With age increasing, the possibility of fatal is increasing. And if a patient has ever been to hospital, ICU or intubated, the possibility also has different levels of increases.<br />
</p>
</div>
<div id="weakness" class="section level1">
<h1>Weakness</h1>
<p>In this paper, I omit the NA sources of infection, but it has the highest amount of infections, so this might be critical. Also, the data-set is too small to trace the real characteristics of COVID-19, since it only has data from Toronto. In the future, I will use a larger and well-specified data to further my study.<br />
</p>
<p>The data in this spreadsheet are subject to change as public health investigations into reported cases and continuous quality improvement initiatives are ongoing, and additional cases continue to be reported. The data will be completely refreshed and overwritten on a weekly basis.<br />
</p>
<p>This tree-based model does not have much precision on predicting even though the testing result is good, and the outcomes are just based on the proportion between each class and total. Because this model is lack of advanced algorithms and sample data, we can only identify some variable influences by it. Of course, in the future, I will develop more perfect model and more developed algorithm to increase the precision.<br />
</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<ul>
<li><a href="https://en.wikipedia.org/wiki/2020_in_Canada#Events_cancelled_as_a_result_of_the_COVID-19_pandemic" class="uri">https://en.wikipedia.org/wiki/2020_in_Canada#Events_cancelled_as_a_result_of_the_COVID-19_pandemic</a></li>
<li><a href="https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection/prevention-risks.html?&amp;utm_campaign=gc-hc-sc-coronavirus2021-ao-2021-0005-9834796012&amp;utm_medium=search&amp;utm_source=google_grant-ads-107802327544&amp;utm_content=text-en-434601690167&amp;utm_term=%2Bcovid" class="uri">https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection/prevention-risks.html?&amp;utm_campaign=gc-hc-sc-coronavirus2021-ao-2021-0005-9834796012&amp;utm_medium=search&amp;utm_source=google_grant-ads-107802327544&amp;utm_content=text-en-434601690167&amp;utm_term=%2Bcovid</a></li>
<li><a href="https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection/health-professionals/interim-guidance-cases-contacts.html" class="uri">https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection/health-professionals/interim-guidance-cases-contacts.html</a></li>
<li><a href="https://www.toronto.ca/home/covid-19/covid-19-protect-yourself-others/covid-19-reduce-virus-spread/" class="uri">https://www.toronto.ca/home/covid-19/covid-19-protect-yourself-others/covid-19-reduce-virus-spread/</a></li>
<li><a href="https://open.toronto.ca/dataset/covid-19-cases-in-toronto/" class="uri">https://open.toronto.ca/dataset/covid-19-cases-in-toronto/</a></li>
<li>Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686,
<a href="https://doi.org/10.21105/joss.01686" class="uri">https://doi.org/10.21105/joss.01686</a></li>
<li>Sharla Gelfand (2020). opendatatoronto: Access the City of Toronto Open Data Portal.
<a href="https://sharlagelfand.github.io/opendatatoronto/" class="uri">https://sharlagelfand.github.io/opendatatoronto/</a>,
<a href="https://github.com/sharlagelfand/opendatatoronto/" class="uri">https://github.com/sharlagelfand/opendatatoronto/</a>.</li>
<li>Terry Therneau and Beth Atkinson (2019). rpart: Recursive Partitioning and Regression Trees. R package version
4.1-15. <a href="https://CRAN.R-project.org/package=rpart" class="uri">https://CRAN.R-project.org/package=rpart</a></li>
<li>Stephen Milborrow (2020). rpart.plot: Plot ‘rpart’ Models: An Enhanced Version of ‘plot.rpart’. R package
version 3.0.9. <a href="https://CRAN.R-project.org/package=rpart.plot" class="uri">https://CRAN.R-project.org/package=rpart.plot</a></li>
</ul>
</div>
